<br>
<font size="+2"> In this notebook, we will be working on questions in the Colab Notebooks section in Module 1. </font>
<br><br>

# Questions on Accessing Data



Let's take a break from learning basic pandas commands and have you practice what you've learned so far. To do this, we will work in this new Colab notebook.
<br><br>
In this notebook, you will read the `city_temperature.csv` datafile; the format of this datafile is the same as the temperature datafile we were using in the video, it just has many more data points because it includes temperature data for the entire world (i.e. rows).

<font color='#FF4500' size="+2"> To set up your DataFrame for these questions, run the cell below. </font>

In [2]:
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

import os
path = "/content/drive/MyDrive/Understanding-the-World-Through-Data/AIMOOC"
os.chdir(path)

import pandas as pd
file_path = "/content/drive/MyDrive/Data/city_temperature.csv"
df2 = pd.read_csv(file_path)

Mounted at /content/drive/

/tmp/ipykernel_957/1922915133.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(file_path)

## Question 1

What's the name of the country at row number 1000000?

In [8]:
# Your code here
df2.loc[1000000,"Country"]

'Yugoslavia'

## Question 2

What is the name of the city that comes last alphabetically?

In [9]:
# Your code here
df2.sort_values(by="City").tail(1)["City"]

961942    Zurich
Name: City, dtype: object

## Question 3

How many data points are there in the US?

In [10]:
# Your code here
df2[df2["Country"]=="US"].shape[0]

1455337

## Question 4

What is the highest temperature in the dataset?

In [11]:
# Your code here
df2["AvgTemperature"].max()

110.0

## Question 5

What is the lowest temperature in the US? This dataset uses -99 as the temperature for missing values. Find the minimum temperature ignoring -99.

In [12]:
# Your code here
df2[(df2["Country"]=="US") & (df2["AvgTemperature"]!=-99)]["AvgTemperature"].min()

-50.0

## Question 6

What is the average August temperature in Beijing?

In [27]:
# Your code here
df2[(df2["City"]=="Beijing") & (df2["Month"]==8)]["AvgTemperature"].mean()

np.float64(77.9541935483871)

## Question 7

What is the city with the highest temperature?

In [15]:
# Your code here
df2.sort_values(by="AvgTemperature",ascending=False).head(1)["City"]

1034962    Kuwait
Name: City, dtype: object

## Question 8

In which year was the temperature in May the highest?

In [35]:
# Your code here


# df2.groupby("Year").mean(numeric_only=True)
df2[(df2["Month"]==5)].sort_values(by="AvgTemperature",ascending=False).head(1)["Year"]

1030148    1999
Name: Year, dtype: int64

In which city was the temperature in May the highest?

In [36]:
# Your code here (hint: make use of the code from the previous question)
df2[(df2["Month"]==5)].sort_values(by="AvgTemperature",ascending=False).head(1)["City"]

1030148    Kuwait
Name: City, dtype: object