<br>
<font size="+2"> In this notebook, we will be working on questions in Colab Notebooks section in Module 1. </font>
<br><br>

In this notebook, we will continue working with `city_temperature.csv` datafile; remember that the format of this datafile is the same as the temperature datafile we were using in the video, it just has many more data points because it includes temperature data for the entire world (i.e. rows).

<font color='#FF4500' size="+2"> To set up your DataFrame for these questions, run the cell below. </font>

In [1]:
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

import os
path = "/content/drive/MyDrive/Understanding-the-World-Through-Data/AIMOOC"
os.chdir(path)

import pandas as pd
file_path = "/content/drive/MyDrive/Data/city_temperature.csv"
df2 = pd.read_csv(file_path)

Mounted at /content/drive/

/tmp/ipykernel_1441/1625756011.py:10: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(file_path)

# Questions on Groupby

We will now take another break from our Basic Pandas commands video and let you practice the groupby command in addition to filtering and other basic commands you tried before.
<br><br>
If you've been away from your notebook for a while, you will need to rerun the commands at the top to load the data into Colab (set up your DataFrame). To rerun the cell, you select the cell and then run it. The [cell](#load-df) you want to rerun is the one for mounting the Google Drive and reading your csv.

## Average Yearly Temperature - Part 1

Create a new DataFrame called, `paris`, that only has data for **Paris**. You'll need to filter the original data for rows whose city matches `"Paris"`. Then use the `paris` DataFrame to create a third DataFrame, called `parismean`, that specifies the average temperature per year in Paris. To do this, you'll need to use the groupby function. Provide the average temperature in Paris for each of the years.

In [13]:
paris = df2[df2["City"]=="Paris"]
parismean = paris.groupby("Year")["AvgTemperature"].mean(numeric_only=True)
parismean

Year
1995    53.742192
1996    52.293169
1997    55.580000
1998    50.317534
1999    54.565753
2000    54.337705
2001    53.944932
2002    52.743014
2003    54.562192
2004    53.585246
2005    53.407671
2006    54.199726
2007    53.572055
2008    52.381694
2009    53.061096
2010    51.648219
2011    55.001918
2012    53.256557
2013    52.088493
2014    53.650411
2015    53.434973
2016    51.122951
2017    54.367945
2018    45.773151
2019    52.208219
2020    49.320149
Name: AvgTemperature, dtype: float64

## Average Yearly Temperature - Part 2

Now that we have the `parismean` DataFrame, we can find the year in which the average temperature was the lowest. To do this, first find the minimum average temperature and save it as a variable called `minparismean`. Then, locate the row in the `parismean` DataFrame whose temperature matches `minparismean`.

Which year had the minimum average temperature in Paris?

In [14]:
minparismean = parismean.min()
minparismean

45.77315068493151

## Number of Days above 80 - Part 1

Create a new DataFrame called `hightemp`, that only has data where the temperature is **above 80 degrees**. You'll need to filter the original data for rows whose temperature is greater than 80. Then use the `hightemp` DataFrame to create a third DataFrame called `cities` that specifies the number of days above 80 per city. To do this, you'll need to use the groupby function. Provide the count for the number of days above 80 degrees for the following cities.

In [17]:
# Your code here
hightemp = df2[df2["AvgTemperature"]>80]
cities = hightemp.groupby("City").count()
cities

              Region  Country  State  Month   Day  Year  AvgTemperature
City
Abidjan         5046     5046      0   5046  5046  5046            5046
Abilene         1942     1942   1942   1942  1942  1942            1942
Abu Dhabi       5441     5441      0   5441  5441  5441            5441
Akron Canton     100      100    100    100   100   100             100
Albany            88       88     88     88    88    88              88
...              ...      ...    ...    ...   ...   ...             ...
Yerevan          340      340      0    340   340   340             340
Youngstown        52       52     52     52    52    52              52
Yuma            1698     1698   1698   1698  1698  1698            1698
Zagreb           244      244      0    244   244   244             244
Zurich            19       19      0     19    19    19              19

[302 rows x 7 columns]

## Number of Days above 80 - Part 2

Now that we have the `cities` DataFrame, we can find the largest of the count values from this DataFrame. To do this, first find the **maximum** count and save it as a variable called `highestcount`. Then, locate the row in the cities DataFrame whose count matches `highestcount`.
<br><br>
Which city had the largest number of days over 80 degrees?

In [19]:
# Your code here
highestcount = cities["AvgTemperature"].max()
highestcount

7751